---

build:
  stage: build
  image: docker:stable
  tags:
    - Linux
    - docker
    - x86_64
  before_script:
    - |
      echo "${DOCKERHUB_ACCESS_TOKEN}" | docker login \
      --username ${DOCKERHUB_USERNAME} \
      --password-stdin
      echo "${CI_JOB_TOKEN}" | docker login \
      --username gitlab-ci-token \
      --password-stdin \
      "${CI_REGISTRY}"
  script:
    - cd dockerfiles
    - |
      docker build \
        -f Dockerfile_${R_ENVIRONMENT}_${R_VERSION}_bioc_${BIOC_VERSION} \
        -t ${CI_REGISTRY_IMAGE}/${R_ENVIRONMENT}_${R_VERSION}_bioc_${BIOC_VERSION}:latest \
        .
    - docker push ${CI_REGISTRY_IMAGE}/${R_ENVIRONMENT}_${R_VERSION}_bioc_${BIOC_VERSION}:latest
  parallel:
    matrix:
      - R_ENVIRONMENT: ["r-ver", "rstudio", "rstudio-local", "tidyverse", "verse"]
        R_VERSION: ["4.1.0", "4.1.1"]
        BIOC_VERSION: ["3.13"]
  timeout: 2 hours
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "schedule"

