#!/usr/bin/env Rscript

# Script that installs additional packages from CRAN
# Takes in the distribution as the first argument.
args <- commandArgs(trailing = TRUE)
distribution <- args[1]

# CRAN packages to install
cran_pkgs <- list(
  tidyverse = c(
    "lintr",
    "spelling",
    "gridExtra",
    "optimx",
    "car",
    "emmeans",
    "lme4",
    "lmerTest",
    "dfoptim",
    "shiny",
    "shinyjs",
    "shinyWidgets",
    "covr",
    "pkgdown",
    "nomnoml",
    "odbc",
    "styler",
    "shinytest",
    "ggmosaic",
    "colourpicker",
    "DT",
    "ggExtra",
    "ggpmisc",
    "sparkline",
    "vistime",
    "ggrepel",
    "kableExtra",
    "cowplot",
    "mcr",
    "DescTools",
    "png",
    "webshot",
    "circlize",
    "Rdpack",
    "pkgdown",
    "ggfortify",
    "vroom",
    "tzdb",
    "Rcpp",
    "cli",
    "stringi",
    "git2r",
    "rcmdcheck",
    "tinytest",
    "igraph",
    "dm",
    "glmmTMB",
    "rstan",
    "rtables",
    "pillar",
    "xfun",
    "globals",
    "checkmate"
  ),
  rstudio = c(
    "callr",
    "devtools",
    "lintr",
    "magrittr",
    "spelling",
    "testthat",
    "withr",
    "glue",
    "dplyr",
    "magrittr",
    "rlang",
    "tibble",
    "knitr",
    "ggplot2",
    "gridExtra",
    "scales",
    "htmltools",
    "tidyr",
    "xml2",
    "rmarkdown",
    "optimx",
    "assertthat",
    "gtable",
    "purrr",
    "forcats",
    "car",
    "emmeans",
    "labeling",
    "lme4",
    "lmerTest",
    "dfoptim",
    "viridisLite",
    "broom",
    "tidyselect",
    "shiny",
    "digest",
    "lifecycle",
    "R6",
    "shinyjs",
    "shinyWidgets",
    "yaml",
    "covr",
    "pkgdown",
    "DBI",
    "httr",
    "nomnoml",
    "odbc",
    "readr",
    "crayon",
    "styler",
    "rvest",
    "shinytest",
    "ggmosaic",
    "colourpicker",
    "DT",
    "ggExtra",
    "ggpmisc",
    "jsonlite",
    "sparkline",
    "vistime",
    "ggrepel",
    "kableExtra",
    "cowplot",
    "mcr",
    "DescTools",
    "fs",
    "gh",
    "png",
    "rvest",
    "webshot",
    "circlize",
    "Rdpack",
    "remotes",
    "pkgdown",
    "ggfortify",
    "vroom",
    "tzdb",
    "Rcpp",
    "cli",
    "stringi",
    "git2r",
    "rcmdcheck",
    "tinytest",
    "igraph",
    "dm",
    "glmmTMB",
    "rstan",
    "rtables",
    "pillar",
    "xfun",
    "globals",
    "checkmate"
  ),
  `rstudio-local` = c(
    "callr",
    "devtools",
    "lintr",
    "magrittr",
    "spelling",
    "testthat",
    "withr",
    "glue",
    "dplyr",
    "magrittr",
    "rlang",
    "tibble",
    "knitr",
    "ggplot2",
    "gridExtra",
    "scales",
    "htmltools",
    "tidyr",
    "xml2",
    "rmarkdown",
    "optimx",
    "assertthat",
    "gtable",
    "purrr",
    "forcats",
    "car",
    "emmeans",
    "labeling",
    "lme4",
    "lmerTest",
    "dfoptim",
    "viridisLite",
    "broom",
    "tidyselect",
    "shiny",
    "digest",
    "lifecycle",
    "R6",
    "shinyjs",
    "shinyWidgets",
    "yaml",
    "covr",
    "pkgdown",
    "DBI",
    "httr",
    "nomnoml",
    "odbc",
    "readr",
    "crayon",
    "styler",
    "rvest",
    "shinytest",
    "ggmosaic",
    "colourpicker",
    "DT",
    "ggExtra",
    "ggpmisc",
    "jsonlite",
    "sparkline",
    "vistime",
    "ggrepel",
    "kableExtra",
    "cowplot",
    "mcr",
    "DescTools",
    "fs",
    "gh",
    "png",
    "rvest",
    "webshot",
    "circlize",
    "Rdpack",
    "remotes",
    "pkgdown",
    "ggfortify",
    "vroom",
    "tzdb",
    "Rcpp",
    "cli",
    "stringi",
    "git2r",
    "rcmdcheck",
    "tinytest",
    "igraph",
    "dm",
    "glmmTMB",
    "rstan",
    "rtables",
    "pillar",
    "xfun",
    "globals",
    "checkmate"
  ),
  `r-ver` = c("devtools"),
  verse = c(
    "lintr",
    "spelling",
    "gridExtra",
    "optimx",
    "car",
    "emmeans",
    "lme4",
    "lmerTest",
    "dfoptim",
    "shinyjs",
    "shinyWidgets",
    "covr",
    "pkgdown",
    "nomnoml",
    "odbc",
    "styler",
    "shinytest",
    "ggmosaic",
    "colourpicker",
    "DT",
    "ggExtra",
    "ggpmisc",
    "sparkline",
    "vistime",
    "ggrepel",
    "kableExtra",
    "cowplot",
    "mcr",
    "DescTools",
    "png",
    "circlize",
    "Rdpack",
    "pkgdown",
    "ggfortify",
    "vroom",
    "tzdb",
    "Rcpp",
    "cli",
    "stringi",
    "git2r",
    "rcmdcheck",
    "glmmTMB",
    "rstan",
    "rtables",
    "pillar",
    "xfun",
    "globals",
    "checkmate"
  )
)

# Get diff of installed and uninstalled packages for
# idempotent package installation
new_pkgs <-
  cran_pkgs[[distribution]][!(cran_pkgs[[distribution]] %in% installed.packages()[, "Package"])]

# Install only uninstalled packages
if (length(new_pkgs))
  install.packages(new_pkgs,
                   Ncpus = parallel::detectCores())

# Conditionally install phantonJS
if (require("shinytest")) {
  shinytest::installDependencies()
  file.copy(shinytest:::find_phantom(), "/usr/local/bin/phantomjs")
}

# Conditionally install TinyTex
if (require("tinytex")) {
  tinytex::install_tinytex()
  # There are symlinks created for the Tex bins,
  # which we will move to a central location
  system("mv ~/bin/* /usr/local/bin/")
  # Remove the bin directory
  unlink("~/bin", recursive = TRUE)
}

